name: Konstantinos Ampountolas
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "https://kampountolas.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
